// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeSfZYscpr5--Io0QJAEGfZeJF2Cn8FHg',
    appId: '1:329503117791:web:72b921511129a54a2d346a',
    messagingSenderId: '329503117791',
    projectId: 'smash-gift-43af1',
    authDomain: 'smash-gift-43af1.firebaseapp.com',
    storageBucket: 'smash-gift-43af1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ-IFxItyP19mspzyyMINnQu0cnl4fs0g',
    appId: '1:329503117791:android:799e7db1a64c7cd42d346a',
    messagingSenderId: '329503117791',
    projectId: 'smash-gift-43af1',
    storageBucket: 'smash-gift-43af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbgaj7ETAYIZdUNy0SXB_pg2O_R51LASM',
    appId: '1:329503117791:ios:356657ad667958c02d346a',
    messagingSenderId: '329503117791',
    projectId: 'smash-gift-43af1',
    storageBucket: 'smash-gift-43af1.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

}